<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sirius_tty_sensors</name>
  <version>0.1.0</version>
  <description>Sirius sensors communicating using TTY</description>

  <maintainer email="patryk.filip.gryz@rxsio.com">Patryk Filip Gryz</maintainer>
  <author email="patryk.filip.gryz@rxsio.com">Patryk Filip Gryz</author>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <exec_depend>python3-pydantic</exec_depend>
  <exec_depend>python3-serial</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>