<robot xmlns:xacro="http://wiki.ros.org/xacro">
<xacro:include filename="rim.urdf.xacro" />
<xacro:macro name="wheel" params="prefix:='' material material_rim flip:=false mechanical:=${xacro.load_yaml('$(find sirius_description)/config/mechanical.yaml')} inertial:=${xacro.load_yaml('$(find sirius_description)/config/inertial/wheel.yaml')}">
  <xacro:property name="_prefix" value="${prefix + '_' if prefix else ''}"/>
  
  <link name="${_prefix}wheel">
    <visual>
      <material name="${material}" />
      <geometry>
        <mesh filename="package://sirius_description/meshes/sirius/wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0 0 0" />
    </visual>
    <inertial>
      <mass value="${inertial['wheel_mass']}"/>
      <inertia ixx="${inertial['wheel_inertia']['ixx']}" ixy="${inertial['wheel_inertia']['ixy']}" ixz="${inertial['wheel_inertia']['ixz']}" iyy="${inertial['wheel_inertia']['iyy']}" iyz="${inertial['wheel_inertia']['iyz']}" izz="${inertial['wheel_inertia']['izz']}"/>
    </inertial>
    <collision>    
      <geometry>
        <cylinder length="${mechanical['wheel_width']}" radius="${mechanical['wheel_radius']}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </collision>
  </link>
  
  <xacro:rim prefix="${_prefix}outer" material="${material_rim}" />
  <xacro:rim prefix="${_prefix}inner" material="${material_rim}" />
  <joint name="${_prefix}outer_rim_joint" type="fixed">
    <parent link="${_prefix}wheel"/>
    <child link="${_prefix}outer_rim"/>
    <origin xyz="0 ${ (1 - 2*flip) * (mechanical['wheel_width'] + mechanical['rim_width'])/2} 0" />
  </joint>
  <joint name="${_prefix}inner_rim_joint" type="fixed">
    <parent link="${_prefix}wheel"/>
    <child link="${_prefix}inner_rim"/>
    <origin xyz="0 ${ (2*flip - 1) * (mechanical['wheel_width'] + mechanical['rim_width'])/2} 0" />
  </joint>

  <gazebo reference="${_prefix}wheel">
    <visual>  
      <xacro:element xacro:name="xacro:${material}" />
    </visual> 
      <kd>5000.0</kd>
      <kp>1e3</kp>
      <max_vel>0.1</max_vel>
  </gazebo>
</xacro:macro>
</robot>