# Weight was roughly measured and inertia was calculated by hand.
# Would be good idea to double check it.
wheel_mass: 0.73414
wheel_inertia: 
  ixx: 0.01509
  ixy: 0
  ixz: 0
  iyy: 0.02529
  iyz: 0
  izz: 0.01509