links:
  names:
    - "waist"
    - "shoulder"
    - "elbow"
    - "wrist_lift"
    - "wrist_turn"
    - "wrist_spin"
  lengths:
    - 0.080
    - 0.445
    - 0.468
    - 0.060
    - 0.245

  limits:
    - [-3.0, 3.0]
    - [-1.57, 1.57]
    - [0, 3.14]
    - [-1.57, 1.57]
    - [-1.57, 1.57]
    - [-1000.0, 1000.0]
