sirius:
    wheels_left:
      hardware_interface:
        joints:
          - front_left_wheel_joint
          - back_left_wheel_joint
    wheels_right:
      hardware_interface:
        joints:
          - front_right_wheel_joint
          - back_right_wheel_joint
    controller:
      wheels_left_state:
        type: joint_state_controller/JointStateController
        publish_rate: 5
        joints:
          - front_left_wheel_joint
          - back_left_wheel_joint
      wheels_right_state:
        type: joint_state_controller/JointStateController
        publish_rate: 5
        joints:
          - front_right_wheel_joint
          - back_right_wheel_joint
      wheels:
        type        : "diff_drive_controller/DiffDriveController"
        left_wheel  : 
          - 'front_left_wheel_joint'
          - 'back_left_wheel_joint'
        right_wheel : 
          - 'front_right_wheel_joint'
          - 'back_right_wheel_joint'
        publish_rate: 30               # default: 50
        pose_covariance_diagonal : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        twist_covariance_diagonal: [0.2, 0.05, 0.05, 0.0, 0.0, 1.0]
        wheel_separation : 0.577
        wheel_radius : 0.110
        cmd_vel_timeout: 1.0
        linear:
          x:
            has_velocity_limits: true
            max_velocity: 1.0
            has_acceleration_limits: true
            max_acceleration: 1.25
        angular:
          z:
            has_velocity_limits: true
            max_velocity: 1.0
            has_acceleration_limits: true
            max_acceleration: 3.14
        enable_odom_tf: false