grid_map_topic: /traversability_estimation/traversability_map

grid_map_visualizations:

  - name: traversability_grid
    type: occupancy_grid
    params:
      layer: traversability
      data_min: 0.9
      data_max: 0.5
